server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
#    url: "jdbc:mysql://mysql-2a060b51-vutuananhctnd117-fdb9.h.aivencloud.com:10746/defaultdb?useSSL=true&requireSSL=true&serverTimezone=UTC"
#    username: avnadmin
#    password: AVNS_YQN8D6-2Hi5ZjVWqk_A
    url: "jdbc:mysql://localhost:3306/identity-service"
    username: root
    password: 0825326281Tanh
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "LtEB5JwxpJemFG66f2hlzoGGbQ4QVd5yQT+HdfdfY8GZ8Q5flBayguixIVK7RxpK\r\n"