server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity-service"
    username: root
    password: 0825326281Tanh
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "LtEB5JwxpJemFG66f2hlzoGGbQ4QVd5yQT+HdfdfY8GZ8Q5flBayguixIVK7RxpK\r\n"